### ISSUE TITLE
Start streaming when clicking "Start streaming"

### ISSUE THREAD

**Issue by sorenisanerd** [CatxFish/obs-v4l2sink#38]
I can't imagine a usecase where you want to both stream to e.g. Youtube AND stream to v4l2sink, so why isn't v4l2sink just a regular streaming output?

**Comment by MarioMey** [comment]
I never did it... but I think that it is usefull to have both, stream and v4l2sink at the same time.

Imagine you are in an remote interview with a person. You are the one who organize the interview, the one who asks, the one who controls OBS and the one who stream the video to YouTube. You connect with the guest with Zoom (using v4l2sink). You take his/her image with OBS, mount it in the scene and stream it to YouTube. Because of the delay of streaming and for the gest to know what's happening in the show, it is necessary that he/her can see the output. So, he/she can dialog confortably.

**Comment by sorenisanerd** [comment]
Yeah, that makes sense. Thanks.

**Comment by MarioMey** [comment]
Actually, I'm streaming with a sign language translator, live. 

This is from yesterday, I'm saying hello to her.
![vlcsnap-2020-07-21-15h04m12s083](https://user-images.githubusercontent.com/4954109/88090132-7dbd9a00-cb63-11ea-9c64-c7b109d54118.jpg)
